# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    exception_funnel:
        class: AppBundle\Service\ExceptionFunnel
        arguments: ['%exception_filter_words%']
    mail_fetcher:
        class: AppBundle\Service\MailFetcher
        arguments: ['@exception_funnel', '%mailuser%', '%mailpassword%', '%mailbox']
